name: Test Pass

env:
  artifact_name: biligo-live-ws-development

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test_pass:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Test
      run: go test -v ./...
  build_linux:
    if: github.event_name == 'push'
    needs: [ test_pass ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [ "amd64", "arm64", "arm" ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build Linux
        run: go build -o ./dist/biligo-ws-live-${{ matrix.goarch }}
        env:
          GOARCH: ${{ matrix.goarch }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.artifact_name }}
          path: 'dist'

  build_windows:
    if: github.event_name == 'push'
    needs: [ test_pass ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build Windows
        run: go build --buildmode=exe -o ./dist/biligo-ws-live.exe

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.artifact_name }}
          path: 'dist'
